### ISSUE TITLE
Use wrong branch name for cloning `master` instead `main`

### ISSUE THREAD

**Issue by papanito** [hspaans/ansible-galaxy-action#199]
**Describe the bug**

Git clone happens on `master` rather `main`, which is set as default branch

```
Starting import: task_id=918362, repository=papanito/ansible-role-cloudflared 
 
Task "918362" failed: Command '['git', 'clone', '--quiet', '--depth', '1', '--branch', 'master', 'https://github.com/papanito/ansible-role-cloudflared.git', '/var/tmp/galaxy/imports/tmpr4z6riu2']' returned non-zero exit status 128. 
```

**To Reproduce**
Use [this workflow](https://github.com/papanito/github-actions-workflows/blob/main/.github/workflows/ansible-roles-release.yml)

```
name: Create release

on:
  workflow_call:
    secrets:
      gh_token:
        required: true
      galaxy_api_key:
        required: true

jobs:
   ...
  import-role:
    runs-on: ubuntu-latest
    needs: create-release
    steps:
    - name: Publish Ansible role to Galaxy
      uses: hspaans/ansible-galaxy-action@v1
      with:
        api_key: ${{ secrets.galaxy_api_key }}
```

**Expected behavior**
Role clones the correct branch

**Screenshots**

![image](https://github.com/hspaans/ansible-galaxy-action/assets/15034009/a20f12f1-0882-47e7-879c-15ac2fb0dc86)

**Additional context**
N/A
